on:
  workflow_call:
    inputs:
      repository:
        description: Repository name; format = [organization]/[repository-name]
        required: true
        type: string
      solution-location:
        description: Additional folders to get to solution file location
        required: false
        default: Source/
        type: string
      replacements-in:
        type: string
        description: Replacement placeholders separated by a semicolon (;)
        required: false
        default: ""
      software-version:
        type: string
        description: The semantic version of the software
        required: true
    secrets:
      aws-region:
        description: The region in AWS to push to
        required: true
      aws-access-key-id:
        description: The AWS Access Key ID
        required: true
      aws-secret-access-key:
        description: The AWS Secret Access Key
        required: true
      pat-github:
        description: GitHub PAT
        required: true
      replacements-out:
        description: Replacement values separated by a semicolon (;)
        required: false
jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: "v2.0.0"
          repository: JayTechNL/jaytech-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - name: Replace placeholders
        uses: ./workflow/actions/jta-replacements
        with:
          replacements-in: ${{inputs.replacements-in}}
          replacements-out: ${{secrets.replacements-out}}
      - name: Upload prepared repository
        uses: actions/upload-artifact@v3
        with:
          name: workflow
          path: workflow
  build:
    needs: preparations
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: .NET build
        shell: bash
        run: dotnet build workflow/repository/${{inputs.solution-location}} --configuration Release
  test:
    name: Test .NET
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Test .NET
        shell: bash
        run: dotnet test workflow/repository/${{inputs.solution-location}} --configuration Release
  test-optional:
    name: Test .NET (optional)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Stryker Solution
        uses: ./workflow/actions/jta-stryker-solution
        with:
          projects: JayTech.Services.JayTech.Api
          test-project: JayTech.Services.JayTech.Tests.Unit
  continuous-delivery:
    name: Continuous Delivery
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Push Docker Image To AWS
        uses: ./workflow/actions/jta-docker-push-aws
        with:
          container-name: ${{ github.event.repository.name }}
          software-version: ${{inputs.software-version}}
          aws-access-key-id: ${{secrets.aws-access-key-id}}
          aws-secret-access-key: ${{secrets.aws-secret-access-key}}
          aws-region: ${{secrets.aws-region}}
  sync-gitops:
    name: Sync GitOps
    needs: continuous-delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          ref: "development"
          repository: CROW-NL/asfalt-impuls-tool-environment
          token: ${{secrets.pat-github}}
          path: workflow/gitops
      - name: Set GitOps version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "workflow/gitops/version.yml"
          propertyPath: "version.api"
          value: ${{inputs.software-version}}
          commitChange: false
          updateFile: true
      - name: Push to GitOps
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.pat-github }}
        with:
          source-directory: workflow/gitops
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ github.event.repository.name }}-gitops
          commit-message: Updated ${{ github.event.repository.name }} version to ${{inputs.software-version}}
          target-branch: development
