on:
  workflow_call:
    inputs:
      repository:
        description: Repository name; format = [organization]/[repository-name]
        required: true
        type: string
      solution-location:
        description: Additional folders to get to solution file location
        required: false
        default: Source/
        type: string
    secrets:
      pat_github:
        description: GitHub PAT
        required: true

jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat_github }}
          path: repository
      - name: Upload prepared repository
        uses: actions/upload-artifact@v3
        with:
          name: repository
          path: repository
  build:
    needs: preparations
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: repository
          path: repository
      - name: .NET build
        shell: bash
        run: |
          cd repository/${{inputs.solution-location}}
          dotnet build --configuration Release
