on:
  workflow_call:
    inputs:
      repository:
        description: Repository name; format = [organization]/[repository-name]
        required: true
        type: string
    secrets:
      pat_github:
        description: GitHub PAT
        required: true

jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat_github }}
          path: repository
      - uses: actions/upload-artifact@v3
        with:
          name: repository
          path: repository
  build:
    needs: preparations
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: repository
          path: repository
