on:
  workflow_call:
    inputs:
      repository:
        description: Repository name; format = [organization]/[repository-name]
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  preparations:
    name: Prepare repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: my-org/my-private-tools
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: my-tools