on:
  workflow_call:
    inputs:
      contract-version:
        type: string
        description: The version of the contract to use for NuGet
        required: true
      package-name:
        type: string
        description: The name of the package for NuGet
        required: true
      dotnet-version:
        type: string
        description: The version .NET to use for NuGet
        required: false
        default: "6.x"
      oas-location:
        type: string
        description: The location to the OAS file
        required: false
        default: src/oas.yaml
    secrets:
      pat-github:
        description: GitHub PAT
        required: true
      azure-api-key:
        description: The Azure API key
        required: true
      azure-source:
        description: The Azure Artifacts Source
        required: true
      azure-feed:
        description: The Azure Artifacts Feed
        required: true
jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: "v2.1.0"
          repository: JayTechNL/jaytech-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - name: Upload prepared repository
        uses: actions/upload-artifact@v3
        with:
          name: workflow
          path: workflow
  build:
    needs: preparations
    name: Build Contract
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: jta-swagger-codegen
        uses: ./workflow/actions/jta-swagger-codegen
        with:
          input-file: ${{inputs.oas-location}}
          language: csharp
          package-name: ${{inputs.package-name}}
          package-version: ${{inputs.contract-version}}
          return-i-collection: true
          model-package: Model
          net-core-project-file: true
          target-framework: v5.0
          optional-emit-default-values: true
          validatable: false
      - uses: actions/upload-artifact@v3
        with:
          name: contract-package
          path: ./workflow/actions/jta-swagger-codegen/output/src
  continuous-delivery:
    name: Continuous Delivery
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: contract-package
          path: ./workflow/actions/jta-nuget-push-azure/contract-package
      - name: jta-nuget-push-azure
        uses: ./workflow/actions/jta-nuget-push-azure
        with:
          software-version: ${{inputs.contract-version}}
          dotnet-version: ${{inputs.dotnet-version}}
          project-folder: ./workflow/actions/jta-nuget-push-azure/contract-package/
          azure-api-key: ${{secrets.azure-api-key}}
          azure-source: ${{secrets.azure-source}}
          azure-feed: ${{secrets.azure-feed}}
