on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: The name of the package for NuGet
        required: true
      dotnet-version:
        type: string
        description: The version .NET to use for NuGet
        required: false
        default: "7.x"
      oas-location:
        type: string
        description: The location to the OAS file
        required: false
        default: src/oas.yaml
    secrets:
      pat-github:
        description: GitHub PAT
        required: true
      azure-api-key:
        description: The Azure API key
        required: true
      azure-source:
        description: The Azure Artifacts Source
        required: true
      azure-feed:
        description: The Azure Artifacts Feed
        required: true
jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
      - name: Checkout JayTech actions
        uses: actions/checkout@v3
        with:
          ref: master
          repository: JayTechNL/jaytech-tools-github-actions
          token: ${{ secrets.pat-github }}
          path: workflow/actions
      - name: Upload prepared repository
        uses: actions/upload-artifact@v3
        with:
          name: workflow
          path: workflow
  build:
    needs: preparations
    name: Build Contract
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - id: semver
        uses: ./workflow/actions/gitversion-semver
      - name: Set contract version
        run: sed -i "s/{{OAS_VERSION}}/${{ steps.semver.outputs.semantic-version }}/g" ./workflow/repository/${{inputs.oas-location}}
      - name: Build OAS Contract
        uses: ./workflow/actions/dotnet-build-contract
        with:
          file-path: ${{inputs.oas-location}}
          package-name: ${{inputs.package-name}}
          package-version: ${{ steps.semver.outputs.semantic-version }}
      - uses: actions/upload-artifact@v3
        with:
          name: contract-package
          path: ./workflow/actions/dotnet-build-contract/output/src/
  continuous-delivery:
    name: Continuous Delivery
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: workflow
          path: workflow
      - name: Download prepared repository
        uses: actions/download-artifact@v3
        with:
          name: contract-package
          path: ./workflow/actions/nuget-push-azure/contract-package
      - name: nuget-push-azure
        uses: ./workflow/actions/nuget-push-azure
        with:
          software-version: ${{ steps.semver.outputs.semantic-version }}
          dotnet-version: ${{inputs.dotnet-version}}
          project-folder: ./workflow/actions/nuget-push-azure/contract-package/
          azure-api-key: ${{secrets.azure-api-key}}
          azure-source: ${{secrets.azure-source}}
          azure-feed: ${{secrets.azure-feed}}
      - name: Tag & Release
        uses: actions/create-release@v1        
        if: contains('refs/heads/master', github.ref)
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.semver.outputs.semantic-version }}
          tag_name: ${{ steps.semver.outputs.semantic-version }}     
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
