on:
  workflow_call:
    inputs:
      app-id:
        type: string
        description: Application ID (for Play Store)
        required: false
        default: ""
      replacements-in:
        type: string
        description: Replacement placeholders separated by a semicolon (;)
        required: false
        default: ""
      source-folder:
        type: string
        description: Root folder of the source code
        required: false
        default: "./workflow/repository"
      build-android:
        type: boolean
        description: Run Quasar build for android?
        required: false
        default: false
      build-electron:
        type: boolean
        description: Run Quasar build for electron?
        required: false
        default: false
      build-ios:
        type: boolean
        description: Run Quasar build for ios?
        required: false
        default: false
      build-web:
        type: boolean
        description: Run Quasar build for web?
        required: false
        default: false
    secrets:
      pat-github:
        description: GitHub PAT
        required: true
      play-store-json:
        description: Google Play Store JSON
        required: true
      replacements-out:
        description: Replacement values separated by a semicolon (;)
        required: false

jobs:
  quasar-build-android:
    if: ${{inputs.build-android}}
    uses: JayTechNL/jaytech-tools-github-workflows/.github/workflows/quasar-android.yml@master
    with:
      app-id: nl.jaytech.app
    secrets:
      play-store-json: ${{ secrets.PLAY_STORE_JSON }}
      pat-github: ${{ secrets.pat-github }}

  quasar-build-web:
    if: ${{inputs.build-web}}
    uses: JayTechNL/jaytech-tools-github-workflows/.github/workflows/quasar-web.yml@master
    secrets:
      pat-github: ${{ secrets.pat-github }}
      
  create-release:
    if: ${{ always() }}
    needs: ["quasar-build-android", "quasar-build-web"]
    runs-on: ubuntu-latest
    steps:
      - name: Download web contents      
        uses: actions/download-artifact@v1      
        with:
          name: quasar-build-web
          path: ./output/web
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 0.0.1
          tag_name: 0.0.1          
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
      - name: Upload quasar-web to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.pat-github }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/quasar-web.tar.gz
          asset_name: quasar-web.tar.gz
          asset_content_type: application/gzip
    
